### ISSUE TITLE
GEO property issue

### ISSUE THREAD

**Issue by MitchBred** [spatie/icalendar-generator#10]
Hi,

The [GEO ](https://www.kanzaki.com/docs/ical/geo.html) (->coordinates) property is now a comma but that is not working. 

This works well: 
[GEO](https://www.kanzaki.com/docs/ical/geo.html): Latitude;Longitude

**Comment by rubenvanassche** [comment]
A new release was tagged https://github.com/spatie/icalendar-generator/releases/tag/0.1.1 Thanks!
