### ISSUE TITLE
ALARM component TRIGGER does not work with recurring events

### ISSUE THREAD

**Issue by ankurk91** [spatie/icalendar-generator#12]
Hi,

I have an recurring event that looks like
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:product-1-stage
NAME:product-1
X-WR-CALNAME:product-1

BEGIN:VEVENT
UID:955fa5f486d429d9eaed0ede1cb447d2c63cd5d7
SUMMARY:Test event
DESCRIPTION:laravel meetup 
LOCATION:new delhi
DTSTART:20200103T035200
DTEND:20200103T045200
DTSTAMP:20191226T025458
TRANSP:OPAQUE
CLASS:PUBLIC
RRULE:FREQ=WEEKLY;UNTIL=20220103T235959;BYDAY=MO,TU,WE,TH,FR

BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Test event
TRIGGER;VALUE=DATE-TIME:20200103T025200
END:VALARM

END:VEVENT

END:VCALENDAR
```

Notice the `TRIGGER` property has hard coded date time,
When we try to import this in MacOS  Calendar app, all of imported events shows same alert date_time.

But if we change the `TRIGGER` property to like `PT{$minutes}M`
```
TRIGGER:-PT60M
```
It works as expected. 
Now it show alert `60` minutes before each of imported event.

Let me know your thoughts.

**Comment by rubenvanassche** [comment]
Hi @ankurk91,

I've just added some extended support for Alerts, let me know what you think!

https://github.com/spatie/icalendar-generator/commit/d62ac1eb7ef19e7ee16bfde496540718bb2a8d80

**Comment by ankurk91** [comment]
@rubenvanassche 

It worked for me, please tag a new version.

Thanks again.

**Comment by rubenvanassche** [comment]
https://github.com/spatie/icalendar-generator/releases/tag/0.1.2
