### ISSUE TITLE
Filename for embedded attached files

### ISSUE THREAD

**Issue by reboot1983** [spatie/icalendar-generator#142]
**✏️ Describe the bug**
When adding base64 encoded files as an attachment to the ics file it shows as 'unknown' file in the .ics file. It makes no difference if I add the mimetime as parameter in Event::create()->embeddedAttachment()

The [ICS format looks like it can support filenames](https://icalendar.org/iCalendar-RFC-5545/3-8-1-1-attachment.html). I can also work around the issue by replacing the 'attach' part with x-filename like:

`$calenderFileContent = str_replace('ATTACH;ENCODING=BASE64;VALUE=BINARY:', 'ATTACH;ENCODING=BASE64;VALUE=BINARY;X-FILENAME=' . $filename . ':', $calenderFileContent);`

**✅ Expected behavior**
Is there perhaps an option or possibility to add the filename? Maybe as a parameter of the embeddedAttachment method?

**🖥️ Versions**

iCalendar generator: 8.2.0
PHP: 7.4

**Comment by rubenvanassche** [comment]
When adding a base64 attachment you probably should disable `needsEncoding`, I cannot find anything online about x-filename existing. Would love to add it but cannot find it in official RFC's or stackoverflow issues which are most of the times rich of information about these special Ical properties.
