### ISSUE TITLE
Please release new Tag with fixed EventStatus

### ISSUE THREAD

**Issue by adrichel** [spatie/icalendar-generator#16]
Hello,

thank you for this package, it comes in very handy with my current project and I appreciate your work - but I've got a small issue I'd like to complain about: The EventStatus class in the tag 1.0.0 is non-conforming with RFC 5545 and this was already fixed in the master branch. Please release a new tag with this fix so I don't have to include this package as "dev-master".

Thanks

**Comment by rubenvanassche** [comment]
Hi @adrichel,

Nice to hear you like the package, thought I had already released a new version but didn't 😞. I just added a new release!

**Comment by adrichel** [comment]
That was quick, thank you very much :)
