### ISSUE TITLE
X-ADDRESS: comma's need to be escaped

### ISSUE THREAD

**Issue by lowerends** [spatie/icalendar-generator#17]
Hi,

We noticed that Google Calendar does not accept the generated ICS-file when `X-ADDRESS` is not escaped. It is accepted by Apple Calendar though.

Currently, this package generates this, which is not accepted by Google Calendar:
`X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS=Samberstraat 69D, 2060 Antwerp, Belgium;X-APPLE-RADIUS=72;X-TITLE=Spatie:51.2343;4.4287`

The following is accepted by both Google Calendar and Apple Calendar:
`X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS=Samberstraat 69D\, 2060 Antwerp  \, Belgium;X-APPLE-RADIUS=72;X-TITLE=Spatie:51.2343;4.4287`

I'm willing to create a PR of course, but I'm not sure where to look exactly. Any hints are welcome!

Cheers

**Comment by lowerends** [comment]
Thinking further about this, should all the parameters be escaped by default, just like the in the `textProperty` function?

**Comment by rubenvanassche** [comment]
Hi @lowerends,

I think you can reuse the code within `TextProperty` for the `Parameters`, I welcome PR's 😄

**Comment by lowerends** [comment]
Perfect, I'll make a PR!
