### ISSUE TITLE
Outlook calendar import generates date error

### ISSUE THREAD

**Issue by victor-priceputu** [spatie/icalendar-generator#22]
When we are trying to import the calendar into Outlook we are presented with the following errors:

Task 'Internet Calendar Subscriptions' reported error (0x00040020) : 'The VEVENT, "Custom Event", defined near line 24, contains a floating DTEND. Outlook supports floating time for all-day events only. Double-click to open this item.'

```
$calendar = Calendar::create('Assessments Calendar')
            ->refreshInterval(5)

$event = Event::create('Custom Event')
            ->description('Random description')
            ->startsAt(Carbon::now())
            ->endsAt(Carbon::now()->addHour())
            ->address('Random Address', 'Venue location')
            ->coordinates(1, 1);

$calendar->event($event)
 ->get();
```

When adding timezones to the calendar it fixes this but it creates some issues with the hours for us so we are not using it.

Also, thank you for the other fix :)

Edit: This was encountered on Outlook on Windows 10

**Comment by rubenvanassche** [comment]
Hi @victor-priceputu,

Thanks for the issue, it seems like Outlook does not like local time and always requires timezones to be defined. So there is no simple fix for this issue besides adding timezones. If you have issues with that, then I would recommend always working with the UTC timezone(when saving something in the database for example) or sending this calendar out. Only when a time is presented or collected from a user you concert it to the appropriate timezone. 

As for the package, maybe we should use the UTC timezone by default. If we encounter other dates that are not UTC then we should concert them to UTC. By that convention we can always provide a timezone and Outlook won't complain.

But that's a quite breaking feature and would require some work, so I'm adding this to a list to consider for version 2.0.

I will close this issue for now, hopefully we can fix this in the future!

**Comment by Perturbatio** [comment]
Hi, could the UTC timezone option not be added to a config item which is disabled by default and so not break existing implementations?  It could become the default in 2.0.

**Comment by rubenvanassche** [comment]
Hi @Perturbatio,

I don't think we should add too much config options, this will only make the package more complicated. I've started an issue #24 where we'll start drawing out the future for the package. Hopefully I can start on v2 soon ...
