### ISSUE TITLE
URL into EVENT

### ISSUE THREAD

**Issue by dgillier** [spatie/icalendar-generator#26]
Hello,

I'd like to know if it's possible to add an URL to an EVENT ?

Thanks for your help,
Denis

**Comment by rubenvanassche** [comment]
Hi @dgillier,

It seems that a URL can be defined on(https://tools.ietf.org/html/rfc5545#section-3.8.4.6), I will accept a tested PR that adds this functionality.

**Comment by rubenvanassche** [comment]
This is fixed with release 1.0.5! thanks to @Enaah!
