### ISSUE TITLE
Events with timezones are not valid

### ISSUE THREAD

**Issue by milepanic** [spatie/icalendar-generator#27]
Generating events with timezones generate this code
```
DTSTART;TZID=+01:00:20200211T170003
DTEND;TZID=+01:00:20200214T100026
DTSTAMP;TZID=Europe/Berlin:20200821T172102
```
which [iCalendar Validator](https://icalendar.org/validator.html) shows they are not valid. Removing TZID from DTSTART and DTEND would be valid:
```
DTSTART:20200211T170003
DTEND:20200214T100026
DTSTAMP;TZID=Europe/Berlin:20200821T172102
```

**Comment by rubenvanassche** [comment]
Hi @milepanic,

You're right the calendar is not correct according to the validator:

> Invalid TZID value or missing VTIMEZONE component (Europe/Brussels)

As you can see, we're missing a VTIMEZONE component, these components are not supported by the package at this moment. I'm working on icalendar-generator v2 and this should add support for these components and can automatically generate them. But there's still a lot of work to do in the next weeks. I'm hoping to release it as soon as possible!

The second example you provided is also not correct, from the RFC:

> The parameter MUST be specified on properties with a DATE-TIME value if the DATE-TIME is not either a UTC or a "floating" time. Failure to include and follow VTIMEZONE definitions in iCalendar objects may lead to inconsistent understanding of the local time at any given location.

If you really need this functionality now, you could always implement a VTIMEZONE subcomponent(https://github.com/spatie/icalendar-generator#appending-subcomponents) and add it to this version of the package until v2 comes out.

Hope that answers your question, I'm gonna close this issue for now. But please let me know if you have any question.
