### ISSUE TITLE
Invalid TZID value or missing VTIMEZONE component (Europe/Paris)

### ISSUE THREAD

**Issue by vince83110** [spatie/icalendar-generator#33]
Hello,

I have this event :

```
$event = Calendar::create()
	->event(Event::create("Your booking")
		->startsAt($this->shopBooking->date_start->timezone('Europe/Paris'))
		->endsAt($this->shopBooking->date_end->timezone('Europe/Paris'))
		->createdAt($this->shopBooking->created_at->timezone('Europe/Paris'))
		->address($this->shopBooking->parking->parkingAddress->address .', '. $this->shopBooking->parking->parkingAddress->city)
		->withTimezone()
	);
```

But when I want to open the .ics file into Outlook, it still have 2 hours more than the original date.

In the file, I have : 

```
DTSTART;TZID=Europe/Paris:20201021T183037
DTEND;TZID=Europe/Paris:20201021T191507
```

But I have `20:30` & `21:15` on my Outlook event. And when I try to validate the .ics file, I have these 2 errors : 

```
Invalid TZID value or missing VTIMEZONE component (Europe/Paris) near line # 4
Reference: 3.2.19. Time Zone Identifier
Invalid TZID value or missing VTIMEZONE component (Europe/Paris) near line # 4
Reference: 3.2.19. Time Zone Identifier
```

How can I have to correct timezone ?

**Comment by rubenvanassche** [comment]
Hi @vince83110,

At the moment the package has no support for VTIMEZONE components, some clients require these. I'm working on v2 version of the package: https://github.com/spatie/icalendar-generator/tree/v2 which adds support for theses components. And will automatically generate them. It will take some time to finish v2 (I've been quite busy the last months but my plan is to start working on it again next week).

A temporary solution  could be to implement the VTIMEZONE components yourself using: https://github.com/spatie/icalendar-generator/tree/master#appending-subcomponents.

I hope to release v2 as soon as possible the branch is already quite stable so you could also try using that, but I wouldn't recommend it in production.
