### ISSUE TITLE
Timezone offset invalid for Google Calendar

### ISSUE THREAD

**Issue by johnnyhertogs2** [spatie/icalendar-generator#37]
In the exported ICS string, the timezone offsets are displayed as:

TZOFFSETFROM:0200

Google won't accept the ICS file. When I change it manually to:

TZOFFSETFROM:+0200

It is working. I think positive offsets should be prefixed with a + sign.

**Comment by rubenvanassche** [comment]
Hi @johnnyhertogs2,

version 2.0.2 should fix this!
