### ISSUE TITLE
Not supporting for outlook and enable to edit alert minute before property

### ISSUE THREAD

**Issue by nikhiladgokar12** [spatie/icalendar-generator#41]
We have integrated this plugin into our application facing the below issues:
1. The alertMinutesBefore() property is not working for us. default it takes 10 minutes alert, not able to change it to 30 minutes.
2. We are adding the Location URL for the meeting but the where property won't be reflecting in a google calendar.
3. Not support this .ics file for outlook calendar.
4. Need action property is not working.

I am eager to receive your feedback as soon as possible.

**Below is the example of the .ics file for reference**
-----------------------------------
BEGIN:VCALENDAR
VERSION:2.0
PRODID:spatie/icalendar-generator
NAME:Interview With: Global Compass
X-WR-CALNAME:Interview With: Global Compass
LOCATION:https://us02web.zoom.us/j/85041344729
TRANSP:OPAQUE
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=
 true:mailto:mchaudhari@cemtrexlabs.com
BEGIN:VTIMEZONE
TZID:Asia/Calcutta
BEGIN:STANDARD
DTSTART:20200508T164636
TZOFFSETFROM:+0500
TZOFFSETTO:+0500
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:UTC
BEGIN:STANDARD
DTSTART:20200508T111636
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
UID:60193494bdb93
DTSTAMP;TZID=UTC:20210203T000000
SUMMARY:Reymundo Goyette's Interview for Developer Position with Global Com
 pass
DESCRIPTION:Reymundo Goyette's Interview for Developer Position with Global
  Compass
DTSTART;TZID=Asia/Calcutta:20210203T120000
DTEND;TZID=Asia/Calcutta:20210203T130000
ORGANIZER;CN=Nikhil Adgokar:MAILTO:nadgokar@cemtrexlabs.com
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Interview With: Global Compass is going to start in 30 minutes
TRIGGER:-PT30M
END:VALARM
END:VEVENT
END:VCALENDAR

**Comment by freekmurze** [comment]
Hi, 

we aren't experiencing this issue ourselves, and will not invest time in it soon.

Feel free to submit a PR that fixes this for you.
