### ISSUE TITLE
`endsAt` needs to be provided in order to use `fullDay()` method 

### ISSUE THREAD

**Issue by ramicbenjamin** [spatie/icalendar-generator#43]
Hi Spatie people! 

First of all, thank you for providing such a great libraries and tools for all of us developers out there, especially for this library that is really powerful and easy to use. 

I updated this library in my project to `2.1.0` version that was recently released and found one issue. 

Namely, previously, if you wanted to create an `Event` for full day, you weren't required to specify an end date of that event, you could just put `fullDay()` after `startsAt()` and that would mean that given event will take a full day on a given `startsAt()` date.  Unfortunately, after updating to `2.1.0` version, that is not possible, and you need to specify the `endsAt()` as well, if you want to use `fullDay()`. 

If you don't specify it, creation of `Event` fails in `Event.php` file at line `343`. Is this intentional behavior for some reason, or it shouldn't work like that? It makes more sense to me that you don't have to specify the end date, as start date + full day properties are enough to construct full day event. 

Following code displays that (was working in version `1` and doesn't work in version `2`):

```php
use Spatie\IcalendarGenerator\Components\Calendar;
use Spatie\IcalendarGenerator\Components\Event;

Calendar::create('Laracon online')
    ->event(Event::create('Creating calender feeds')
        ->startsAt(new DateTime('6 March 2019 15:00'))
        ->fullDay()
    )
    ->get();
```

Thank you for taking look at this.

**Comment by rubenvanassche** [comment]
Hi @ramicbenjamin,

This actually wasn't a feature at all, but hey I think it is a useful addition to the package. So I've added support for creating a full day event without specifying an end date, you can find this updated code in version 2.1.1.
