### ISSUE TITLE
Popup does not open in the native Android app

### ISSUE THREAD

**Issue by panfil3** [spatie/icalendar-generator#45]
On android phones a file is generated and the download begins, and then when opening the downloaded file offers to record the event in the Google calendar. Is it possible to immediately open a popup for writing to the calendar, as it is implemented on the iPhone?

**Comment by rubenvanassche** [comment]
Hi @panfil3,

This looks like an implementation from the operating system, I'm afraid there's nothing we as developer can do about it 😢
