### ISSUE TITLE
Add more properties to EVENT

### ISSUE THREAD

**Issue by ankurk91** [spatie/icalendar-generator#8]
Hi,

It would be nice to have these properties too.

* [ORGANIZER](https://www.kanzaki.com/docs/ical/organizer.html)
* [ATTENDEE](https://www.kanzaki.com/docs/ical/attendee.html)
* [EXDATE](https://www.kanzaki.com/docs/ical/exdate.html)

**Comment by MitchBred** [comment]
Hi,

It would be nice if this could also be used.

- [CLASSIFICATION](https://www.kanzaki.com/docs/ical/class.html)
- [GEO](https://www.kanzaki.com/docs/ical/geo.html)
- [TRANSP](https://www.kanzaki.com/docs/ical/transp.html)
- [LOCATION](https://www.kanzaki.com/docs/ical/location.html)
- [PRODID ](https://www.kanzaki.com/docs/ical/prodid.html)(changeable)

**Comment by ankurk91** [comment]
I think GEO and LOCATION is already there.
I agree that PROD ID should not be hard coded.

**Comment by rubenvanassche** [comment]
Hi guys,

You can now add properties to components (https://github.com/spatie/icalendar-generator#extending-the-package). The PRODID can now also be changed. In the future it is a plan to support a few of these properties but that might take some time.

Thanks for the suggestions!

**Comment by rubenvanassche** [comment]
In the latest version (0.2.0) I've added some extra properties:

- ORGANIZER
- ATTENDEE
- CLASSIFICATION
- TRANSP

Can you guys check them out and let me know what you think about it?

Thanks!

**Comment by ankurk91** [comment]
@rubenvanassche

Thanks, it worked.

Can you add `RAW` TextPropertyType, which does not escape anything?

**Comment by MitchBred** [comment]
Thanks @rubenvanassche !!

**Comment by rubenvanassche** [comment]
@ankurk91 I've added a thrid boolean argument to `TextPropertyType` that can disable escaping.

In other news: we've just released v1! 🎉

**Comment by umairali** [comment]
I am trying to change the default value of PRODID but the default value is not changing and TextProperty is adding the same key again.


```
Calendar::create()
          ->appendProperty(
              TextProperty::create('PRODID', 'site 1')
          )
          ->event(
              Event::create("Session - " . $name)
                      ->uniqueIdentifier(mt_rand())
                      ->startsAt(new \DateTime($startDatetime))
                      ->endsAt(new \DateTime($endDatetime))
          )
          ->description($description . " " . $url)
          ->withoutTimezone()
          ->get();

```

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:spatie/icalendar-generator
DESCRIPTION:<div>wtwertwe</div>
X-WR-CALDESC:<div>wtwertwe</div>
PRODID:site 1
BEGIN:VEVENT
UID:428472589
DTSTAMP:20210613T154115Z
SUMMARY:Session - ret 1222
DTSTART:20210608T134500Z
DTEND:20210608T141000Z
END:VEVENT
END:VCALENDAR
```

**Comment by rubenvanassche** [comment]
Hi @umairali,

You can change PRODID as follows:

```php
$calendar->productIdentifier('blabla');
```

**Comment by umairali** [comment]
thank you @rubenvanassche 

I am adding HTML tag in the description but the calendar is not decoding the tag and showing it as a text

**Comment by rubenvanassche** [comment]
Hi @umairali,

I don't think you should add HTMl to the description of a calendar: https://stackoverflow.com/questions/854036/html-in-ical-attachment

You could add the `X-ALT-DESC` property but I don't think a lot of clients support it.

**Comment by umairali** [comment]
I am adding html in X-ALT-DESC but the apple calendar is not supporting it.

**Comment by rubenvanassche** [comment]
Yeah, I don't think Apple Mail supports any HTML in a calendar 😞
